### ISSUE TITLE
how to allowable/adding id (as integer) in array data

### ISSUE THREAD

**Issue by harry-promogata** [8manos/wc-city-select#10]
hi Mantis..

how to allowing id adding id in our array, then we just store the id of value to database (billing_city).. not text value.

like here: 
   var data = [{ id: 0, text: 'enhancement' }, { id: 1, text: 'bug' }, { id: 2, text: 'duplicate' }, { id: 3, text: 'invalid' }, { id: 4, text: 'wontfix' }];
  
from here:

$cities['XX'] = array(
		'YYY' => array(
			'City ',
			'Another City'
		),
		'ZZZ' => array(
			'City 3',
			'City 4'
		)
	);

thanks, best regard

**Comment by Mantish** [comment]
hi, I don't really understand what you're saying
Can you explain what's the problem you're trying to solve?

**Comment by harry-promogata** [comment]
my case, i want to save the id of value to billing_city, not name of city.. but id of city..
please help me sir

**Comment by harry-promogata** [comment]
i'm sorry for my english..

**Comment by harry-promogata** [comment]
i fixed this..
thanks Mantis
