### ISSUE TITLE
Cities not populated in Chrome in Select2

### ISSUE THREAD

**Issue by Amanbhatia** [8manos/wc-city-select#11]
I activated the plugin and pasted the below code.
add_filter( 'wc_city_select_cities', 'my_cities' );
function my_cities( $cities ) {
	$cities['IN'] = array(
		'Noida ',
		'Ghaziabad'
	);
	return $cities;
}

For unknown reason, it works in safari. But it does not work on chrome, mac.
I dont see any javascript error in console.

**Comment by Mantish** [comment]
Hi @Amanbhatia do you still have issues with this?

**Comment by Amanbhatia** [comment]
I actually gave up on it. I might revisit it in few days.
