### ISSUE TITLE
Add Denmark

### ISSUE THREAD

**Issue by jonasskafte** [8manos/wc-city-select#19]
Hi there,

Hope you are well.

Firstly, thanks for providing such a great plugin to the WP community – it's much appreciated!

I'd like to suggest adding Denmark as a new location. There are no states or counties in Denmark, but perhaps we could connect the zip-/postcodes to the different cities? If that's not possible, then it would still be useful to just add the cities as a dropdown searchable list instead of the standard text field.

I'd love to simply add this as a pull request myself, but I am not sure exactly how to create the file in the correct and easiest way. However I've managed to pull all the postcodes and cities in Denmark into a CSV file – perhaps that's useful? Here it is: https://goo.gl/ipe4sz

I hope you'll consider helping me add this location so that we can make this great plugin even more relevant to more people! 😃

Many thanks!

Jonas

**Comment by Mantish** [comment]
Hi Jonas,
Unfortunately there's no easy way to link postcodes ans cities with the plugin.
If you want to add just the cities as a dropdown, you can do it as explained in the [plugin description](https://wordpress.org/plugins/wc-city-select/).
You can also add them to the plugin code in the cities folder and do a pull request.
The format would be:
```
$cities['DK'] = array(
    'City ',
    'Another City'
);
```

**Comment by jonasskafte** [comment]
Hi there @Mantish,

Thanks for your response. I've now made a pull request. I hope I've done it correctly – would you mind taking a look? Here it is: [https://github.com/8manos/wc-city-select/pull/20](https://github.com/8manos/wc-city-select/pull/20)

Many thanks!

Jonas

**Comment by Mantish** [comment]
thanks!
I left you a comment

**Comment by Mantish** [comment]
Cities added in #20 
Thanks @jonasskafte
