### ISSUE TITLE
WC City Issue

### ISSUE THREAD

**Issue by mustafamsy** [8manos/wc-city-select#30]
Hi,
I have one critical problem. When user navigate to the checkout page and select their state, the city field does not refresh and not active and I have to refresh the entire page to take effect. Also, when switching between states, the cities does not change. Also, why city field come before state, it should after state field.

https://foodyano.com/checkout/

I have added the states to function.php like so:

/*
* SA
* As per ISO_3166
* https://en.wikipedia.org/wiki/ISO_3166-2:SA
* https://www.iso.org/obp/ui/#iso:code:3166:SA
* 
*/
function custom_woocommerce_states( $states ) {
$states['SA'] = array(
'SA-01' => 'منطقة الرياض',
'SA-02' => 'منطقة مكة المكرمة',
'SA-03' => 'منطقة المدينة المنورة',
'SA-04' => 'المنطقة الشرقية',
'SA-05' => 'منطقة القصيم',
'SA-06' => 'منطقة حائل',
'SA-07' => 'منطقة تبوك',
'SA-08' => 'منطقة الحدود الشمالية', 
'SA-09' => 'منطقة جازان',
'SA-10' => 'منطقة نجران',
'SA-11' => 'منطقة الباحة',
'SA-12' => 'منطقة الجوف',
'SA-14' => 'منطقة عسير'
);
return $states;
}

All stats showing up fine and are grouped correctly in the function.php file but I have the above issue as I explained earlier. Can you tell me what I am doing wrong?

**Comment by Mantish** [comment]
Hi, is this still an issue?
