### ISSUE TITLE
auto-update wp.org from github

### ISSUE THREAD

**Issue by rwkyyy** [8manos/wc-city-select#36]
@Mantish you or I can integrate this service: https://wppusher.com/ so when there are new releases/updates on the master branch, they get pushed to wp.org/plugins.

**Comment by Mantish** [comment]
hey, that's not what that service does. It is for wordpress sites to update a plugin from the git repo directly.
I'm afraid publishing in wordpress still has to be done manually with SVN

**Comment by rwkyyy** [comment]
https://gist.github.com/philbuchanan/8188898 we could give this a shot, still has to be run manually.

p.s. sorry, misread the capabilities of the service.
