### ISSUE TITLE
Renaming of the plugin

### ISSUE THREAD

**Issue by rwkyyy** [8manos/wc-city-select#38]
Apparently, the current [Wordpress.org policies](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#17-plugins-must-respect-trademarks-copyrights-and-project-names) there are issues with the WP/WC/WordPress/WooCommerce naming of the plugin.

We should consider renaming of this plugin on the Wordpress.org repo (also we should do an update on the WP repo).

**Comment by Mantish** [comment]
The name of the plugin doesn't include any trademarks

**Comment by rwkyyy** [comment]
@Mantish it includes "WC" short for WooCommerce, they don't like that apparently (tried to upload a plugin earlier this month).

**Comment by rwkyyy** [comment]
```
Trademarks apply to the following aspects of your plugin:

• The Display Name - You may not begin the display name with someone else's trademarked (or commonly recognized) term
• All Images - You may not use trademarked logos/images in your banner, screenshots, logos, etc

In order to comply with trademark law, we need you to update the readme file and the main plugin file to no longer infringe on their trademark.

This means your display name cannot begin with WC, Woo, or WooCommerce.
```

**Comment by Mantish** [comment]
Hi man, thanks for sharing. I'm gonna wait until I receive a notification to do such change
