### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by rwkyyy** [8manos/wc-city-select#39]
The fields in the checkout are english and cannot be translated (current state), we can either:
1. use .po/.mo translation and [l18n translations](https://codex.wordpress.org/I18n_for_WordPress_Developers)
2. set up custom meta (more work) and allow the users to input their labels

p.s. I don't know how reliable is the 2nd point and how much work it involves, 1st one should be easy.

**Comment by Mantish** [comment]
The first method would be better. This was just reported on #37. So I'm closing this one as it's duplicated
