### ISSUE TITLE
Activate multisite

### ISSUE THREAD

**Issue by maxisosa** [8manos/wc-city-select#43]
// Check if WooCommerce is active
if ( in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {

Add condition

is_multisite() && array_key_exists( 'woocommerce/woocommerce.php', get_site_option( 'active_sitewide_plugins', array() ) )

**Comment by Mantish** [comment]
Hi, thanks for reporting.
I see that you already have a solution. Would you be able to submit a Pull Request?

**Comment by Mantish** [comment]
fixed in #48
