### ISSUE TITLE
when select country , its related cities not load without refreshing page ?

### ISSUE THREAD

**Issue by mueyyed** [8manos/wc-city-select#53]
can you help get this problem done ?

**Comment by Mantish** [comment]
Hi, can you share more details about the problem.
What's your WP and WC version?

**Comment by mueyyed** [comment]
[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]

**Comment by Mantish** [comment]
Please check the Readme for the correct way to define the cities array.
You can also check the files in https://github.com/8manos/wc-city-select/tree/master/cities to see some examples
