### ISSUE TITLE
default Countriy

### ISSUE THREAD

**Issue by mahdi-alavi** [8manos/wc-city-select#6]
hi
if set default Country and remove that field, plugin not work.

```
function itl_change_default_checkout_country() {
    return 'IR';
}
add_filter( 'default_checkout_country', 'itl_change_default_checkout_country' );
```

https://docs.woothemes.com/document/change-the-default-state-and-country-on-the-checkout/

```
function itl_remove_checkout_fields( $fields ) {
    unset( $fields['billing']['billing_country'] );
    unset( $fields['shipping']['shipping_country'] );

    return $fields;
}
add_filter( 'woocommerce_checkout_fields' , 'itl_remove_checkout_fields' );
```

**Comment by Mantish** [comment]
Hi,
I'm not sure what you're trying to do here.
Why would you remove the country fields?
Does the state dropdown work without the country field?

**Comment by mahdi-alavi** [comment]
in woocommerce setting i set "Selling Location" to "Sell to specific countries only" (IRAN)
in this case there is no need for country field
Does the state dropdown work without the country field? NO

**Comment by Mantish** [comment]
Well, I understand your purpose, but I don't see a lot of value on this (you can always hide the country with CSS)
Pull requests are welcome, anyway.
