### ISSUE TITLE
Update readme for Country with no states

### ISSUE THREAD

**Issue by kelecz** [8manos/wc-city-select#7]
Hello there,
have country with no states. Have to put them with no ZZZ or YYY codes as you wrote that functions or how to do it?
Thx in advance!

**Comment by Mantish** [comment]
Hi, 
You just have to write a one level array, using your country code:

```
add_filter( 'wc_city_select_cities', 'my_cities' );
function my_cities( $cities ) {
    $cities['XX'] = array(
        'City ',
        'Another City'
    );
    return $cities;
}
```

**Comment by kelecz** [comment]
Great, thank you. I'll try.
Here is Serbian city list(file). Please check it and correct mistakes.
[RS.txt](https://github.com/8manos/wc-city-select/files/257187/RS.txt)

**Comment by kelecz** [comment]
Ok, I understand now... I have to put all cities in functions file because I don't know how to load them in custom plugin.  Maybe you will do it because I am nice guy.... :)
My situation is on pictures, I can't found solution on google...
Please help. THX
![screen](https://cloud.githubusercontent.com/assets/19222604/15151223/912ae0ee-16d0-11e6-825b-770173814cb1.png)
![screen](https://cloud.githubusercontent.com/assets/19222604/15151226/96376364-16d0-11e6-9307-cecaa394b526.png)

**Comment by kelecz** [comment]
Ok, I found and resolve warning.
Line 139 in wc-city-select.php line should look like this:
`foreach ((array) $dropdown_cities as $city_name ) {`
and there is no warning. Thx to http://stackoverflow.com/questions/2630013/invalid-argument-supplied-for-foreach .
Hope this will help to someone.
I am on localhost; W10 PC; newest WP, custom template.

**Comment by kelecz** [comment]
There are new warnings... uh   

![screenshot-localhost 2016-05-12 13-24-44](https://cloud.githubusercontent.com/assets/19222604/15213157/b5e8ffc6-1845-11e6-96e4-96a5647337c0.png)

**Comment by kelecz** [comment]
Thank you. Please see this:
![screenshot-localhost 2016-05-12 22-58-19](https://cloud.githubusercontent.com/assets/19222604/15230277/2519b9d6-1895-11e6-8006-013793fa5986.png)
