### ISSUE TITLE
add new dropdown field under city

### ISSUE THREAD

**Issue by harry-promogata** [8manos/wc-city-select#9]
hi manos..
this is a great plugin..

now i want to add extra field (dropdown too), base (chained) by selected city.
this field is populated subdistricts (sub of city).

can you help me sir?
thanks for your advise

**Comment by Mantish** [comment]
Hi, this sounds like a very specific case, so I don't think we should add it to the plugin.
You can try post this in the support forum: https://wordpress.org/support/plugin/wc-city-select

**Comment by harry-promogata** [comment]
hi Mantish, thanks for reply
i has solved this case.. 
![subdistrict-chained](https://cloud.githubusercontent.com/assets/15105937/20082546/3a8924d8-a589-11e6-8f01-7b1de3251194.jpg)
